#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/lutador

###

POST http://localhost:3333/lutador
Content-Type: application/json

{
    "nome": "soligo",
    "peso": "80",
    "idade": "18"
}

###

PUT http://localhost:3333/lutador/1998f15a-d0b3-4e08-ae1c-49e2e1ff8df3
Content-Type: application/json

{
    "nome": "soligo",
    "peso": "90",
    "idade": "15"
}

###

DELETE http://localhost:3333/users/id
